### ISSUE TITLE
JsonSyntaxException adding data source to Windows app

### ISSUE THREAD

**Issue by SteveMunson** [sprutton1/GrimdarkFutureBattlescribe#114]
Trying to add data source (https://grimdark-future.s3.amazonaws.com/index.bsi) in Windows app results in the following error:

Details:

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 22
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:180)
	at com.google.gson.Gson.fromJson(Gson.java:755)
	at com.google.gson.Gson.fromJson(Gson.java:721)
	at com.google.gson.Gson.fromJson(Gson.java:670)
	at com.google.gson.Gson.fromJson(Gson.java:642)
	at net.battlescribe.a.c.e.d(BattleScribe:463)
	at net.battlescribe.desktop.common.RepositorySourceWindowController.a(BattleScribe:221)
	at net.battlescribe.desktop.common.RepositorySourceWindowController.access$downloadRepositorySource(BattleScribe:22)
	at net.battlescribe.desktop.common.RepositorySourceWindowController$a.a(BattleScribe:247)
	at net.battlescribe.desktop.common.RepositorySourceWindowController$a.call(BattleScribe:245)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

-------------------- Caused By --------------------

java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 22
	at com.google.gson.stream.JsonReader.expect(JsonReader.java:339)
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:322)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:168)
	at com.google.gson.Gson.fromJson(Gson.java:755)
	at com.google.gson.Gson.fromJson(Gson.java:721)
	at com.google.gson.Gson.fromJson(Gson.java:670)
	at com.google.gson.Gson.fromJson(Gson.java:642)
	at net.battlescribe.a.c.e.d(BattleScribe:463)
	at net.battlescribe.desktop.common.RepositorySourceWindowController.a(BattleScribe:221)
	at net.battlescribe.desktop.common.RepositorySourceWindowController.access$downloadRepositorySource(BattleScribe:22)
	at net.battlescribe.desktop.common.RepositorySourceWindowController$a.a(BattleScribe:247)
	at net.battlescribe.desktop.common.RepositorySourceWindowController$a.call(BattleScribe:245)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by SteveMunson** [comment]
User error
